CREATE TABLE securities (
    id UUID PRIMARY KEY,
    symbol VARCHAR(8) UNIQUE NOT NULL,
    name TEXT NOT NULL
);

CREATE TABLE bars (
    s_id VARCHAR(8) NOT NULL,
    ts TIMESTAMPTZ NOT NULL,
    o NUMERIC(12,4) NOT NULL,
    h NUMERIC(12,4) NOT NULL,
    l NUMERIC(12,4) NOT NULL,
    c NUMERIC(12,4) NOT NULL,
    v INTEGER NOT NULL,
    txns INTEGER NOT NULL,
    PRIMARY KEY (s_id, ts)
);
