apiVersion: 1

datasources:
  - name: TimescaleDB
    type: postgres
    url: timescaledb:5432
    user: postgres
    secureJsonData:
      password: postgres
    jsonData:
      database: postgres
      sslmode: disable
      maxOpenConns: 10
      maxIdleConns: 4
      connMaxLifetime: 14400
      postgresVersion: 1700
      timescaledb: true
    editable: true
