name: Formatting & Linting

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  goimports:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Run make imports and save output
        run: |
          make imports > goimports.txt
          if [ -s goimports.txt ]; then
            echo "The following files have import issues and must be fixed:" && cat goimports.txt
            exit 1
          fi
